export const POST_SEARCH_QUERY = "POST_SEARCH_QUERY"; 
export const FAILED_POST_SEARCHQUERY ="FAILED_POST_SEARCHQUERY";
export const FETCHING_DATA = "FETCHING_DATA"; 
export const FAILED_FETCHING_DATA = "FAILED_FETCHING_DATA";
export const SORT_COLUMN = "SORT_COLUMN";
export const REMOVE_ROW = "REMOVE_ROW";
export const FAILED_SORT = "FAILED_SORT";
